<?php
/*
 * OnfonMediaSMSGatewayLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace OnfonMediaSMSGatewayLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://api.onfonmedia.co.ke/v1/sms';

    /**
     * Network Layer Access Key
     * @var string
     */
    public static $accessKey = 'ACCESS_KEY';

    /**
     * Used for authentication purpose and pass this parameter in URL encoded format.
     * @var string
     */
    public static $apiKey = 'API_KEY';

    /**
     * Used for authentication purpose and pass this parameter in URL encoded format.
     * @var string
     */
    public static $clientId = 'CLIENT_ID';
}
